project:
  type: website

website:
  title: "Daniel J. Card"
  navbar:
    left:
      - href: index.qmd
      - research.qmd

format:
  html:
    theme:
      dark: cyborg
      light: zephyr 
    css: styles.css
    toc: true



